# Generated by Django 4.2.14 on 2024-08-04 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Максимум 100 символов', max_length=200, verbose_name='Название группы')),
                ('slug', models.SlugField(help_text='Максимум 200 символов', max_length=200, unique=True, verbose_name='Краткое название группы')),
                ('description', models.TextField(blank=True, help_text='Максимум 300 символов', null=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headliner', models.TextField(help_text='заголовок поста', null=True, verbose_name='заголовок')),
                ('text', models.TextField(help_text='основной текст поста', null=True, verbose_name='текст')),
                ('pub_date', models.DateTimeField(auto_now_add=True, help_text='дата публикации поста', null=True, verbose_name='дата публикации')),
                ('image', models.ImageField(blank=True, upload_to='posts/', verbose_name='Картинка')),
                ('author', models.ForeignKey(help_text='имя автора поста', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='автор')),
                ('group', models.ForeignKey(blank=True, help_text='название группы поста', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='posts.group', verbose_name='группа')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(help_text='автор на которого подписались', on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL, verbose_name='автор')),
                ('user', models.ForeignKey(help_text='имя подписчика', on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL, verbose_name='подписчик')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='текст комментария', null=True, verbose_name='текст')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='дата публикации комментария', null=True, verbose_name='дата публикации')),
                ('answer_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.comment', verbose_name='Предыдущий комментарий')),
                ('author', models.ForeignKey(help_text='имя автора комментария', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='автор')),
                ('post', models.ForeignKey(help_text='пост, связанный с комментарием', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.post', verbose_name='пост')),
            ],
        ),
    ]
